#!/usr/bin/env python3
"""Build a kernel-anchored metabolism review sheet.

The script does not call a model. It formats recent daily-memory fragments and
the three review questions needed for crystallization/weathering/discharge.
By default it avoids embedding private memory text in the committed artifact.
Run with --include-private-text locally when the owner wants a full review deck.
"""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path


DEFAULT_MEMORY_DIR = Path("/Users/lizeyu/.openclaw/workspace/memory")
ARTIFACT_DIR = Path(__file__).resolve().parent
REPO_ROOT = ARTIFACT_DIR.parents[3]
DEFAULT_KERNEL_DIR = REPO_ROOT / "examples" / "zeyu-kernel"
DEFAULT_OUTPUT = ARTIFACT_DIR / "metabolism-probe-output.md"
DATE_FILE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}\.md$")


@dataclass(frozen=True)
class KernelEntry:
    entry_id: str
    title: str
    status: str
    privacy: str


@dataclass(frozen=True)
class Fragment:
    source: str
    index: int
    text: str

    @property
    def digest(self) -> str:
        return hashlib.sha256(self.text.encode("utf-8")).hexdigest()[:12]

    @property
    def words(self) -> int:
        return len(re.findall(r"\S+", self.text))


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text
    raw = text[4:end].strip().splitlines()
    data: dict[str, str] = {}
    for line in raw:
        if ":" in line and not line.startswith(" "):
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip()
    return data, text[end + 5 :]


def first_heading(body: str, fallback: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def load_kernel_entries(kernel_dir: Path) -> list[KernelEntry]:
    entries: list[KernelEntry] = []
    for path in sorted(kernel_dir.glob("*/*.md")):
        if path.name == "_partition.md" or path.parts[-2] == "ledger":
            continue
        text = path.read_text(encoding="utf-8")
        frontmatter, body = parse_frontmatter(text)
        if "type" not in frontmatter:
            continue
        rel = path.relative_to(kernel_dir).as_posix()
        entries.append(
            KernelEntry(
                entry_id=rel,
                title=first_heading(body, path.stem.replace("-", " ")),
                status=frontmatter.get("status", ""),
                privacy=frontmatter.get("privacy", ""),
            )
        )
    return entries


def latest_memory_files(memory_dir: Path, limit: int, max_bytes: int) -> list[Path]:
    candidates = [p for p in memory_dir.glob("*.md") if DATE_FILE_RE.match(p.name)]
    candidates = [p for p in candidates if p.stat().st_size <= max_bytes]
    return sorted(candidates, key=lambda p: p.name)[-limit:]


def split_fragments(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    parts = [part.strip() for part in re.split(r"\n\s*\n", text) if part.strip()]
    return [part for part in parts if len(part) >= 20]


def load_fragments(memory_dir: Path, days: int, max_bytes: int) -> tuple[list[Path], list[Fragment]]:
    files = latest_memory_files(memory_dir, days, max_bytes)
    fragments: list[Fragment] = []
    for path in files:
        for index, text in enumerate(split_fragments(path), start=1):
            fragments.append(Fragment(path.name, index, text))
    return files, fragments


def render_fragment_text(fragment: Fragment, include_private_text: bool) -> str:
    if include_private_text:
        return fragment.text
    return (
        "_Private text omitted in committed artifact. "
        "Run with `--include-private-text` locally to embed review text._"
    )


def render(
    kernel_dir: Path,
    memory_files: list[Path],
    entries: list[KernelEntry],
    fragments: list[Fragment],
    include_private_text: bool,
) -> str:
    lines: list[str] = [
        "# Metabolism Probe Output",
        "",
        "Generated by `metabolism-probe.py`.",
        "",
        "## Inputs",
        "",
        f"- Kernel: `{kernel_dir}`",
        f"- Daily memory files: {len(memory_files)}",
        f"- Memory fragments: {len(fragments)}",
        f"- Private text embedded: `{str(include_private_text).lower()}`",
        "",
        "### Memory files",
        "",
    ]
    lines.extend(f"- `{path.name}` ({path.stat().st_size} bytes)" for path in memory_files)
    lines.extend(["", "### Kernel entries", ""])
    lines.extend(
        f"- `{entry.entry_id}` — {entry.title} ({entry.status}, {entry.privacy})"
        for entry in entries
    )
    lines.extend(
        [
            "",
            "## Kernel-Anchored Review Sheet",
            "",
            "For each fragment, ask:",
            "",
            "1. 支持哪条 kernel entry？这是结晶信号。",
            "2. 挑战哪条 kernel entry？这是风化信号。",
            "3. 与任何 kernel entry 都无关？如果要留下，凭什么？这是排放信号。",
            "",
        ]
    )

    for fragment in fragments:
        lines.extend(
            [
                f"### {fragment.source}#fragment-{fragment.index}",
                "",
                f"- sha256: `{fragment.digest}`",
                f"- size: {fragment.words} whitespace tokens",
                "",
                "```text",
                render_fragment_text(fragment, include_private_text),
                "```",
                "",
                "| Question | Reviewer answer |",
                "| --- | --- |",
                "| 支持哪条 kernel entry？ |  |",
                "| 挑战哪条 kernel entry？ |  |",
                "| 无关但应留下吗？凭什么？ |  |",
                "",
            ]
        )

    lines.extend(
        [
            "<!-- frequency-baseline:start -->",
            "## Frequency Baseline",
            "",
            "_Run `frequency-probe.py` to replace this section with the TF-IDF baseline._",
            "<!-- frequency-baseline:end -->",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kernel-dir", type=Path, default=DEFAULT_KERNEL_DIR)
    parser.add_argument("--memory-dir", type=Path, default=DEFAULT_MEMORY_DIR)
    parser.add_argument("--days", type=int, default=14)
    parser.add_argument("--max-bytes", type=int, default=200_000)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--include-private-text", action="store_true")
    args = parser.parse_args()

    entries = load_kernel_entries(args.kernel_dir)
    memory_files, fragments = load_fragments(args.memory_dir, args.days, args.max_bytes)
    output = render(
        args.kernel_dir,
        memory_files,
        entries,
        fragments,
        args.include_private_text,
    )
    args.output.write_text(output, encoding="utf-8")
    print(f"Wrote {args.output} with {len(fragments)} fragments.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
